### ISSUE TITLE
Build against Electron v1.7 (ABI 54)

### ISSUE THREAD

**Issue by wingrunr21** [prebuild/prebuild-ci#11]
Hi,

It doesn't look like there's a way to build against Electron v1.7 with ABI 54 since that was never a node version with that ABI. I assume this version needs to be added to the "oddball" versions.

I'm happy to open a PR with [another nested function](https://github.com/prebuild/prebuild-ci/blob/master/index.js#L63-L78) but wanted to ask if that's how you wanted to continue to support "oddballs".

**Comment by juliangruber** [comment]
Thank you for being proactive about it! And I think you spotted the right problem, I think we'll want to introduce an array of oddball versions and use a function to build for them in series. This particular module comes to mind: https://github.com/feross/run-series.

A PR would be absolutely awesome!!!

**Comment by lovell** [comment]
PR for this at https://github.com/prebuild/prebuild-ci/pull/16
