### ISSUE TITLE
Please update `version-changed` to v2.0.0

### ISSUE THREAD

**Issue by mbroadst** [prebuild/prebuild-ci#21]
v2.0.0 of [version-changed](https://github.com/ralphtheninja/version-changed) has a much-needed fix for us, using a relative path for a `package.json` (we happen to be running prebuilds from a deeply nested structure in a git repo). Could you please update `prebuild-ci`?

**Comment by vweevers** [comment]
It also dropped node 6; I guess it's time for `prebuild-ci` to do the same, and bump major.

A PR is welcome.

**Comment by mbroadst** [comment]
Thanks! I made #22 for you, would you like the `engines` to be bumped in this PR as well?

**Comment by mbroadst** [comment]
Looks like it's [already there](https://github.com/prebuild/prebuild-ci/blob/master/package.json#L23)

**Comment by vweevers** [comment]
That'd be great, and also remove 6 from travis.

**Comment by mbroadst** [comment]
@vweevers actually it looks like `version-changed` [supports 6+](https://github.com/ralphtheninja/version-changed/blob/master/package.json#L30), so you shouldn't need a change.

**Comment by vweevers** [comment]
I'm not sure: https://github.com/ralphtheninja/version-changed/commit/b459209cecf8e3bf22462a1c86be864f45889d84

Let's bump anyway.

**Comment by mbroadst** [comment]
done
