### ISSUE TITLE
move to home prebuilders association

### ISSUE THREAD

**Issue by ralphtheninja** [prebuild/prebuild-ci#6]
@juliangruber `prebuild` and `prebuild-install` now lives there and `prebuild-ci` is a bit lonely so can go play there with its friends :man_playing_water_polo: :grinning:

**Comment by piranna** [comment]
They could come home too, we have cookies and a shorter name :-D

**Comment by juliangruber** [comment]
xD

what should i do please someone tell me i'm lost

**Comment by ralphtheninja** [comment]
@juliangruber Hit `Settings` on this repository, scroll down to the bottom and click `Transfer` button. Then proceed to move it to https://github.com/home-prebuilders-association

**Comment by ralphtheninja** [comment]
Or add me as owner and I can do it ;)

**Comment by juliangruber** [comment]
oh I know how to move it, just wasn't sure where it should go. I'll move now

**Comment by juliangruber** [comment]
i'm not admin on this repo

**Comment by zeke** [comment]
> we have cookies and a shorter name

I agree. `home-prebuilders-association` is a mouthful.

**Comment by zeke** [comment]
> we have cookies and a shorter name

I agree. `home-prebuilders-association` is a mouthful.

**Comment by ralphtheninja** [comment]
Point taken. I don't really care as long as we pick one.

**Comment by ralphtheninja** [comment]
Who is the owner of the `prebuild` organization? It's neither @juliangruber nor @mafintosh

**Comment by ralphtheninja** [comment]
The reason I'm wondering is because I'd like the following to happen (sorry for being nit picky):

1. move `prebuild/prebuild-ci` to `home-prebuilders-association/prebuild-ci`
2. remove `prebuild` organization
3. rename `home-prebuilders-association` organization to `prebuild`

Sound ok?

**Comment by zeke** [comment]
> Who is the owner of the `prebuild` organization? 

@piranna, I think. https://github.com/home-prebuilders-association/discussion/issues/1#issuecomment-324251631

**Comment by piranna** [comment]
> Who is the owner of the prebuild organization?
> @piranna, I think. home-prebuilders-association/discussion#1 (comment)

I'm not, it's @juliangruber... but seems I have administrative permissions too, not sure why. If I need to do something there, just ask me, I'm online right now.

**Comment by ralphtheninja** [comment]
@piranna Invited you to `home-prebuilders-association` so you should be able to move `prebuild-ci` now, as in transfer from repo settings

**Comment by piranna** [comment]
> @piranna Invited you to home-prebuilders-association so you should be able to move prebuild-ci now, as in transfer from repo settings

Repo moved, org deleted, and org renamed. I'm an music band man :-P

**Comment by ralphtheninja** [comment]
Awesome music :grinning: :musical_keyboard:
